export {default as HomeLayout } from './homeLayout'
export {default as Landing } from './Landing'
export {default as About } from './About'
export {default as Listings } from './Listings'
export {default as SingleDetail} from './SingleDetail'
export {default as Collections} from './Collections'
export {default as Register} from './Register'
export {default as Login} from './Login'
export {default as Error} from './Error'
export {default as Checkout} from './Checkout'